// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

console.log("\n~~");

var message = "Welcome OCaml";

var names = /* array */[
  "Luke",
  "Mat",
  "Souhe"
];

var numberArr = /* array */[
  1,
  2,
  3
];

var multiplication = Caml_int32.imul;

function multiplicationLab(x, y) {
  return Caml_int32.imul(x, y | 0);
}

function multi9(param) {
  return Caml_int32.imul(9, param | 0);
}

function multi5(param) {
  return Caml_int32.imul(5, param);
}

console.log("~~");

var name = "ReasonML";

var car = "Ferrari";

var laFerrari = /* record */[
  /* weigh */1000.0,
  /* serialNumber */"F140FE",
  /* hours */800,
  /* maxSpeed */349.5,
  /* electric */true
];

var cityAndStreet = /* tuple */[
  "Prague",
  "Kasztanowa",
  40
];

var city = "Prague";

var street = "Kasztanowa";

var number = 40;

var numberList = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var cityList = /* :: */[
  "Prague",
  /* :: */[
    "Wroclaw",
    /* :: */[
      "Paris",
      /* [] */0
    ]
  ]
];

exports.name = name;
exports.message = message;
exports.car = car;
exports.laFerrari = laFerrari;
exports.names = names;
exports.numberArr = numberArr;
exports.cityAndStreet = cityAndStreet;
exports.city = city;
exports.street = street;
exports.number = number;
exports.numberList = numberList;
exports.cityList = cityList;
exports.multiplication = multiplication;
exports.multiplicationLab = multiplicationLab;
exports.multi9 = multi9;
exports.multi5 = multi5;
/*  Not a pure module */
