// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

console.log("\n__Exercise 2__");

function question(ans) {
  if (ans) {
    return "No way!";
  } else {
    return "Yes, of course!";
  }
}

function checkPrize(p) {
  if (p.tag) {
    return "???";
  } else {
    return String(p[0]) + " gold coin";
  }
}

console.log("#6 First win: " + checkPrize(/* Cash */Block.__(1, [123.2])));

console.log("#7 Second win: " + checkPrize(/* Gold */Block.__(0, [123])));

function whatDoYouDo(name, profession, _) {
  return "Welcome " + (name + (
            profession ? " I'm a " + profession[0] : ""
          ));
}

console.log("#8 " + whatDoYouDo("ReasonML", /* Some */["programmer"], /* () */0));

console.log("#9 " + whatDoYouDo("oCaml", /* None */0, /* () */0));

var yourAnswer = /* Yes */0;

var conferenceDuration = /* Days */Block.__(0, [1]);

var xyFloat = /* tuple */[
  1.2,
  1.2,
  "my custom string"
];

var xyInt = /* tuple */[
  2,
  1,
  "end"
];

var youKnowReasonML = /* Some */["Yes, I know!"];

exports.yourAnswer = yourAnswer;
exports.conferenceDuration = conferenceDuration;
exports.xyFloat = xyFloat;
exports.xyInt = xyInt;
exports.youKnowReasonML = youKnowReasonML;
exports.question = question;
exports.checkPrize = checkPrize;
exports.whatDoYouDo = whatDoYouDo;
/*  Not a pure module */
