// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';


console.log("\n__START__");

var hello = "Helo!";

var name = "ReasonML";

var combine = "Helo! ReasonML";

var message = "Welcome OCaml";

var names = /* array */[
  "Luke",
  "Mat",
  "Souhe"
];

var numberArr = /* array */[
  1,
  2,
  3
];

function add(a, b, c) {
  return (a + b | 0) + c | 0;
}

function addLabel(a, b, c) {
  return (a + b | 0) + (c | 0) | 0;
}

function sub(a, b) {
  return a - b | 0;
}

function sub5(param) {
  return 50 - param | 0;
}

var car = "Ferrari";

var laFerrari = /* record */[
  /* weigh */1000.0,
  /* serialNumber */"F140FE",
  /* hours */800,
  /* maxSpeed */349.5,
  /* electric */true
];

var cityAndStreet = /* tuple */[
  "Prague",
  "Kasztanowa",
  40
];

var city = "Prague";

var street = "Kasztanowa";

var number = 40;

var numberList = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* [] */0
    ]
  ]
];

var cityList = /* :: */[
  "Prague",
  /* :: */[
    "Wroclaw",
    /* :: */[
      "Paris",
      /* [] */0
    ]
  ]
];

exports.hello = hello;
exports.name = name;
exports.combine = combine;
exports.message = message;
exports.car = car;
exports.laFerrari = laFerrari;
exports.names = names;
exports.numberArr = numberArr;
exports.cityAndStreet = cityAndStreet;
exports.city = city;
exports.street = street;
exports.number = number;
exports.numberList = numberList;
exports.cityList = cityList;
exports.add = add;
exports.addLabel = addLabel;
exports.sub = sub;
exports.sub5 = sub5;
/*  Not a pure module */
