// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Exercise1$Ex1 = require("./Exercise1.bs.js");

function sum(x, y) {
  return x + y | 0;
}

var $$Math = /* module */[/* multi */Exercise1$Ex1.multiplication];

exports.sum = sum;
exports.$$Math = $$Math;
/* Exercise1-Ex1 Not a pure module */
